In [1]:
=============EDA==========
1) pandas : data frame or data application
2) numpy : numerical python for math operation
3) matplotlib : for plot graphs 
3) seaborn : for plot graphs
4) bokhe : for plots
5) plotly : fot plots 
    
======= machine learning ======
7)scikit learn(sk learn) : ml models
8) stats                 : statistical model
============ data retrive from SQL scrapping======
9)sqlite   : connect with data base
10) beautiful soup : scrap the data from website 
11) websocket   : scrap

========= DEEP LEARNING/ computer vision ====
12) Tensorflow : google
13) keras      : DL models
14) opencv  : image operations
15) pillow(pill)  : image operations 
16) pytorch     :  developed by fb 
17) pretrained models :
    VGG16 
    Mobilenet
    RESNET
    RCNN
    MASKRCNN
    FASTERCNN
    YOLO
    
============ natural language process =======
18)NLTK       : natural language process
19) scipy     : 
20) word2vec (how words converted into vector representation)
21) GloVE     : 
    
============== Hugging face  =============
23) Transformers : BERT 
    
    
============== GENAI models=======
24) openAI+ microsoft : gpt models
25) google : gemini ai
26) amazon : Q
27)meta facebook: meta ai
18)
    
    
    
all are having different packages 
========= langchain =========
29) LangChain   framework


======== Deployment =======
30) flask
31) streamlit
32) django
=========== mlops ===========
34) mlflow
35) kobeflow
35) azure ai service :  azure packages 
36) GCP : GCP packages 

SyntaxError: unmatched ')' (1863130807.py, line 2)

**step-1** 
- create a data frame 

- we will create a data frame 
- we create a data frame using dictionary 

In [4]:
import pandas as pd 

In [5]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [6]:
type(d1)

pandas.core.frame.DataFrame

**STEP-2**
**provide the data**

In [7]:
names = ['tarun', 'surender','mohith']
pd.DataFrame(names)

0
0     tarun
1  surender
2    mohith

In [8]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
pd.DataFrame(zip(names,age))

0   1
0     tarun  20
1  surender  21
2    mohith  22

In [9]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
city=['hyd','hyd','blr']
data = zip(names,age,city)
pd.DataFrame(data)

0   1    2
0     tarun  20  hyd
1  surender  21  hyd
2    mohith  22  blr

**step-3**
**provide the column names**

In [10]:
names = ['tarun', 'surender','mohith']
pd.DataFrame(names,columns=['name'])


name
0     tarun
1  surender
2    mohith

In [11]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
city=['hyd','hyd','blr']
data = zip(names,age,city)
pd.DataFrame(data,columns=['name','age','city'])

name  age city
0     tarun   20  hyd
1  surender   21  hyd
2    mohith   22  blr

In [12]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
city=['hyd','hyd','blr']

pd.DataFrame(zip(names,age,city),columns=['name','age','city'])

name  age city
0     tarun   20  hyd
1  surender   21  hyd
2    mohith   22  blr

**step-4**
- **providing index**

In [13]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
city=['hyd','hyd','blr']
data = zip(names,age,city)
pd.DataFrame(data,columns=['name','age','city'],index=['a','b','c'])

name  age city
a     tarun   20  hyd
b  surender   21  hyd
c    mohith   22  blr

In [14]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
city=['hyd','hyd','blr']

pd.DataFrame(zip(names,age,city),columns=['name','age','city'],index=['a','b','c'])

name  age city
a     tarun   20  hyd
b  surender   21  hyd
c    mohith   22  blr

In [15]:
names = ['tarun', 'surender','mohith']
age=[20,21,22]
pd.DataFrame(zip(names,age,),columns=['name','age',],index=["hyd","hyd","blr"])

name  age
hyd     tarun   20
hyd  surender   21
blr    mohith   22

**step-5**
- **add a new column on existing dataframe**

In [17]:
import pandas as pd 


In [22]:
name=['surender','saketh','rohith']
age=[21,22,23]
city=['chennai','hyd','blr']
df=pd.DataFrame(zip(name,age,city),columns=['name','age','city'],index=['a','b','c'])
df

name  age     city
a  surender   21  chennai
b    saketh   22      hyd
c    rohith   23      blr

In [ ]:
- if you want to add new colum 
- first check how many rows are there 
- for example in above data frame 3 rows 
- your new column also should have 3 rows 
- suppose i want create a new column called salary
- make a list of salary with 3 values 
- salary [10,20,30]
- **syantax** dataframe[column]=list of values 

In [27]:
salary=[100000,200000,300000]
df['salary']=salary
df


name  age     city  salary
a  surender   21  chennai  100000
b    saketh   22      hyd  200000
c    rohith   23      blr  300000

**use case-1**
- create a empty data frame first 
- create a 3 list using listcomprehension
- list1 should have values 1 to 10 
- list 2 square of 1 t0 10
- list3 cube of 1 to 10

In [28]:
import pandas as pd 
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [38]:
l=[i for i in range(1,11)]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
l1=[i*i for i in range (1,11)]
l1

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [40]:
l2=[i*i*i for i in range (1,11)]
l2

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [42]:
df=pd.DataFrame(zip(l,l1,l2),columns=['number','square','cube'])
df

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

**step-6**
- **update the already existed column**

In [ ]:
- create a new 
- update existing column same way only 
- here alos we need to make a list of vallues the number of rows
- craeting a new column name is our choice 
- but updating existing column we need to provide already existed column name only 

In [43]:
l4=[i**4 for i in range(1,11)]
df['cube']=l4
df

number  square   cube
0       1       1      1
1       2       4     16
2       3       9     81
3       4      16    256
4       5      25    625
5       6      36   1296
6       7      49   2401
7       8      64   4096
8       9      81   6561
9      10     100  10000

**step-7**
- **how to drop column**

In [44]:
# how to check the columns 
df.columns

Index(['number', 'square', 'cube'], dtype='object')

- if u want to drop a specific column we will use drop method 
- we already know about difference between keywords and methods 
- keywords will use directly
- methods will come corresponding data frame 
- here the **method name is drop** 
- 

df1.drop()


- in order to drop a column 
- which you want to drop you need to provide 
- axis: represents specified row or column 
    - axis : 0 means rows
    - axis : 1 means column
- inplace : will provide overwrite dataframe or not 
    - inplace : true this indicates over write the data fame 
    - inplcae :False this indicate the modified will be used when you provide new variable called operation

In [50]:
df.drop('cube',axis=1)


number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [55]:
df.drop("cube",axis=1)

KeyError: "['cube'] not found in axis"

In [56]:
df

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [59]:
df.drop("square",axis=1,inplace=True)
df

KeyError: "['square'] not found in axis"

In [3]:
import pandas as pd


In [4]:
name=['surender','saketh','rohith']
age=[21,22,23]
city=['chennai','hyd','blr']
df=pd.DataFrame(zip(name,age,city),columns=['name','age','city'],index=['a','b','c'])
df

name  age     city
a  surender   21  chennai
b    saketh   22      hyd
c    rohith   23      blr

**step-8**

- **drop the row**
- drop the column and row both are similae only 
- the only difference is axis 
    - axis =0 represents rows
    - by default axis =0 available 
    - which means if we provide any value, it will represent column only

In [6]:
df

name  age     city
a  surender   21  chennai
b    saketh   22      hyd
c    rohith   23      blr

In [7]:
df.drop("a")

name  age city
b  saketh   22  hyd
c  rohith   23  blr

In [8]:
import pandas as pd 
l=[i for i in range(1,11)]
l1=[i*i for i in range (1,11)]
l2=[i*i*i for i in range (1,11)]
df=pd.DataFrame(zip(l,l1,l2),columns=['number','square','cube'])
df


number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

In [9]:
df.drop("number ")

KeyError: "['number '] not found in axis"

- if we drop a number we will get error
- by default axis is 0 so it represent about rows 
- but 'number' is column 
- if we want drop the row we need provide the indx

In [12]:
df.drop([4,5])

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

**multiple rows or multiple column always keep in a list**

In [ ]:
df.drop([4,5])

In [14]:
df.drop([0,1],axis=1)

KeyError: '[0, 1] not found in axis'

In [18]:
df.columns[[0,1]]

Index(['number', 'square'], dtype='object')

**step-9**
   **how to select the column**

In [21]:
df[['number']]
# series type
# no colmn name display 
# whenever you see this type : series type


number
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10

In [24]:
type(df['square'])

pandas.core.series.Series

In [25]:
type(df[['square']])

pandas.core.frame.DataFrame

In [26]:
df[['number','square']]

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [27]:
df.number

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: number, dtype: int64

In [28]:
df.square

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
Name: square, dtype: int64

In [ ]:
- df['number'] : series type
- df[['number']] : dataframe
- df.number  : series type

In [32]:
col=['number','square']
df[col]

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [33]:
df['number'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

- all values comes in an array 
- array means it is a list of elements only represents using numpy package 
- genrally elements present in 3 ways 
    - list        : basic representation
    - numpy array : array with numpy package
    - tensor     : tensorflow 
    - torch      : pytorch package

In [34]:
list1=[1,2,3,4,]
list1

[1, 2, 3, 4]

In [35]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [36]:
tensor([1,2,3,4])

NameError: name 'tensor' is not defined

In [38]:
list1=[1,2,3,4 ]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [41]:

l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [43]:
df['number'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [44]:
df['NUMBER']=df['number'].values

In [45]:
df

number  square  cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9
9      10     100  1000      10

In [46]:
# imagine we worked on ml problem
# we got some series of values 
# with that series of values also we can create a dataframe

**step-10**
-**HOW TO SAVE THE DATAFRAME**

- dataframe we can save in 2 formats
    - csv :coma seprated value
    - xlsx: excel format
- in order to save any data 
    - where you want to save directoey name
    - what is the name od the file for storing 
    - what is the extension 
- we already seen same thing file handling session



In [ ]:
# case -1 
#saving file at same location 
# no need to provide directory path 
# directly give only name of the file 

In [57]:
# datafram = df 
df.to_csv('Data1.csv')
df.to_xml('Data1.xlsx')

**STEP-1**
- **HOW TO READ A DTAFRAME**

In [51]:
import pandas as pd 
pd.read_csv('data1.csv')

Unnamed: 0  number  square  cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9
9           9      10     100  1000      10

In [58]:
import pandas as pd 
pd.read_excel("Data1.xlsx")

ValueError: Excel file format cannot be determined, you must specify an engine manually.

**step-12**
-while we sav the datframe 
- automatically a new column will create 
- that we need to avoid 
- permision denied means we need to close the data file from laptop

In [61]:
df.to_excel('Data1.xlsx')

In [62]:
import pandas as pd 
pd.read_excel("Data1.xlsx")

Unnamed: 0  number  square  cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9
9           9      10     100  1000      10

In [63]:
df.to_csv('data1.csv',index=False)
df.to_excel('data1.xlsx',index=False)

In [64]:
import pandas as pd 
pd.read_csv('data1.csv')

number  square  cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9
9      10     100  1000      10